/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GerProj;

import GerProj.controller.ProjectController;
import GerProj.controller.TaskController;
import GerProj.model.Project;
import GerProj.model.Task;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws SQLException  {
        System.out.println(new Main().getGreeting());
        
      
     ProjectController projectController = new ProjectController();
     
     Project project = new Project();
     project.setName("Projeto Teste 24");    
     project.setDescription("Ana ligia");
    // project.setCreatedAt(new Date());
     project.setUpdatedAt(new Date());
      projectController.save(project);
            
            System.out.println("teste do erro");
          //  project.setId(5);
          //  project.setName("Adriano Dezembro");
         //   project.setDescription("Description");
        //    project.setCreatedAt(new Date());
        //    project.setUpdatedAt(new Date());
        //    projectController.update(project);
            
            System.out.println("Projeto atualizado");
            
           // List<Project> projects = projectController.getAll();
            //System.out.println("Total de Projetos = " +projects.size());
            
            
            //TaskController taskController = new TaskController();
            
            //Task task = new Task();
            //task.setIdProject(2);
            //task.setName("Criar tela de aplicação");
           // task.setDescription("Devem ser criadas as telas para cadastros");
            //task.setNotes("Sem notas");
            
            
       
    }
}
